### ISSUE TITLE
clips spazzing rapidly.

### ISSUE THREAD

**Issue by dehelleman** [TGiFallen/Clip_Tool#7]
for a very long time, the visual clip tool has worked with no issues, however after the June 2021 update of Gmod, my clips have started flickering very heavily, and it is giving me a hard time using the tool and even playing gmod, since most dupes i create and use, make use of the visual clip tool

i have attempted everything, going as far as purging every single Gmod file and reinstalling the game clean to see if it would resolve the issue, but to no avail, i hope i can get some help here.

i will include a video that shows my issue, which will be heavily compressed to allow it to be uploaded here, so my apologies for the bad quality of it.

https://user-images.githubusercontent.com/60278271/127216847-85d4d8ac-d7dc-4ba4-b1a2-25a0e9be34f2.mp4

**Comment by dehelleman** [comment]
i have received a tip from a friend, saying it may be related to me installing a new graphics card the same day as the June update for gmod, i am running an RX 6900 XT, i am not sure if this knowledge is of any help, if it is the reason that is.

**Comment by looterz** [comment]
It seems like this kind of issue would be more engine-related than anything the clip tool is doing. It very well could be an AMD card specific issue, or related to the driver version for it installed, etc. Does it happen at all if you change the alpha of a prop normally using the sandbox tool?

**Comment by dehelleman** [comment]
> It seems like this kind of issue would be more engine-related than anything the clip tool is doing. It very well could be an AMD card specific issue, or related to the driver version for it installed, etc. Does it happen at all if you change the alpha of a prop normally using the sandbox tool?

i have tested this just now, it does not happen when i normally change the alpha of a prop

**Comment by looterz** [comment]
Interesting, try using Proper Clipping and see if you still get the render issue https://steamcommunity.com/sharedfiles/filedetails/?id=2256491552

**Comment by dehelleman** [comment]
> Interesting, try using Proper Clipping and see if you still get the render issue https://steamcommunity.com/sharedfiles/filedetails/?id=2256491552

tried it just now, i get the same render issue

**Comment by dehelleman** [comment]
any suggestions?

**Comment by looterz** [comment]
I'm out of ideas, how we render those previews is here https://github.com/ndbeals/Clip_Tool/blob/master/lua/autorun/client/preview.lua#L88

It's possible something in here is causing the artifacts for your GPU/driver setup but it'd be engine and AMD related, less related to the addon itself.
